title: AvocadoNodes systems status page
languageCode: en
params:
  shortDateFormat: 15:04 â€” jul 30
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: Node 1
      link: ne.avocadonodes.com
    - name: Node 2
      link: n2.avocadonodes.com
    - name: Node 3
      link: n3.avocadonodes.com
  dateFormat: July 30, 2021 at 3:04 PM
  disqusShortname: null
  timezoneString: " UTC"
  logo: /images/clearstatus.svg
  description_header: Information about <a class='text-grey-darkest' title='Visit
    example.com' href='https://www.example.com/'>example</a> systems
    operations.<br />Follow us <a class='text-grey-darkest' title='Visit our
    page on Twitter' href='https://www.twitter.com/example'>on Twitter</a> or
    subscribe to <a class='text-grey-darkest' href='%s' >RSS</a><br />to be
    alerted of new events.
  copyrightHolder: Avocado Nodes
  eventsPerPage: 10
  iconType: image/png
  groups:
    - Wings
    - Nodes
  icon: /images/clearstatus.png
  description_footer: ""
